#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : usb-modeswitch
Version  : 2.6.0
Release  : 4
URL      : http://www.draisberghof.de/usb_modeswitch/usb-modeswitch-2.6.0.tar.bz2
Source0  : http://www.draisberghof.de/usb_modeswitch/usb-modeswitch-2.6.0.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: usb-modeswitch-bin = %{version}-%{release}
Requires: usb-modeswitch-license = %{version}-%{release}
Requires: usb-modeswitch-man = %{version}-%{release}
BuildRequires : pkgconfig(libusb-1.0)

%description
For up-to-date and more detailed information (plus a friendly forum) visit
http://www.draisberghof.de/usb_modeswitch

%package bin
Summary: bin components for the usb-modeswitch package.
Group: Binaries
Requires: usb-modeswitch-license = %{version}-%{release}

%description bin
bin components for the usb-modeswitch package.


%package license
Summary: license components for the usb-modeswitch package.
Group: Default

%description license
license components for the usb-modeswitch package.


%package man
Summary: man components for the usb-modeswitch package.
Group: Default

%description man
man components for the usb-modeswitch package.


%prep
%setup -q -n usb-modeswitch-2.6.0
cd %{_builddir}/usb-modeswitch-2.6.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1609781972
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1609781972
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/usb-modeswitch
cp %{_builddir}/usb-modeswitch-2.6.0/COPYING %{buildroot}/usr/share/package-licenses/usb-modeswitch/9c6849cf75e1db73f6bf7825e3a4d334a0801dac
%make_install UDEVDIR=%{buildroot}/usr/lib/udev

%files
%defattr(-,root,root,-)
/usr/lib/udev/usb_modeswitch

%files bin
%defattr(-,root,root,-)
/usr/bin/usb_modeswitch
/usr/bin/usb_modeswitch_dispatcher

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/usb-modeswitch/9c6849cf75e1db73f6bf7825e3a4d334a0801dac

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/usb_modeswitch.1
/usr/share/man/man1/usb_modeswitch_dispatcher.1
